### ISSUE TITLE
Refactor Matchthread structure

### ISSUE THREAD

**Issue by Rukenshia** [Rukenshia/soccerstreams#5]
Structure should be:

```yml
Matchthread:
  Comments:
  - Streams:
    - Stream
```
